GET http://localhost:5146/games

###
GET http://localhost:5146/games/4

###
POST http://localhost:5146/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releasedDate": "2011-11-18"
}


###
PUT  http://localhost:5146/games/4
Content-Type: application/json

  {
    "name": "GTA 5",
    "genre": "Action-adventure",
    "price": 59.00,
    "releasedDate": "2013-09-17"
  }


###
DELETE http://localhost:5146/games/2